package com.xgjgas.gascloud.com.yphx.domain;

import java.io.Serializable;

public class XgjSysUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_join_sys_user_role.ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_join_sys_user_role.F_USER_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String fUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_join_sys_user_role.F_ROLE_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String fRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xgj_join_sys_user_role
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_join_sys_user_role.ID
     *
     * @return the value of xgj_join_sys_user_role.ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_join_sys_user_role.ID
     *
     * @param id the value for xgj_join_sys_user_role.ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_join_sys_user_role.F_USER_ID
     *
     * @return the value of xgj_join_sys_user_role.F_USER_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getfUserId() {
        return fUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_join_sys_user_role.F_USER_ID
     *
     * @param fUserId the value for xgj_join_sys_user_role.F_USER_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setfUserId(String fUserId) {
        this.fUserId = fUserId == null ? null : fUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_join_sys_user_role.F_ROLE_ID
     *
     * @return the value of xgj_join_sys_user_role.F_ROLE_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getfRoleId() {
        return fRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_join_sys_user_role.F_ROLE_ID
     *
     * @param fRoleId the value for xgj_join_sys_user_role.F_ROLE_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setfRoleId(String fRoleId) {
        this.fRoleId = fRoleId == null ? null : fRoleId.trim();
    }
}