package com.xgjgas.gascloud.com.yphx.domain;

import java.io.Serializable;
import java.util.Date;

public class XgjSysUser implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.COMPANY_ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.OFFICE_ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.LOGIN_NAME
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.PASSWORD
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.NO
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.NAME
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.EMAIL
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.PHONE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.MOBILE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.USER_TYPE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.PHOTO
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.LOGIN_IP
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.LOGIN_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private Date loginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.LOGIN_FLAG
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String loginFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.CREATE_BY
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.CREATE_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.UPDATE_BY
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.UPDATE_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.REMARKS
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.DEL_FLAG
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.REGISTRATID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String registratid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.SYSTYPE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String systype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_user.SYSVERSION
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    private String sysversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.ID
     *
     * @return the value of xgj_base_sys_user.ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.ID
     *
     * @param id the value for xgj_base_sys_user.ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.COMPANY_ID
     *
     * @return the value of xgj_base_sys_user.COMPANY_ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.COMPANY_ID
     *
     * @param companyId the value for xgj_base_sys_user.COMPANY_ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.OFFICE_ID
     *
     * @return the value of xgj_base_sys_user.OFFICE_ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getOfficeId() {
        return officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.OFFICE_ID
     *
     * @param officeId the value for xgj_base_sys_user.OFFICE_ID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setOfficeId(String officeId) {
        this.officeId = officeId == null ? null : officeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.LOGIN_NAME
     *
     * @return the value of xgj_base_sys_user.LOGIN_NAME
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.LOGIN_NAME
     *
     * @param loginName the value for xgj_base_sys_user.LOGIN_NAME
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.PASSWORD
     *
     * @return the value of xgj_base_sys_user.PASSWORD
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.PASSWORD
     *
     * @param password the value for xgj_base_sys_user.PASSWORD
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.NO
     *
     * @return the value of xgj_base_sys_user.NO
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.NO
     *
     * @param no the value for xgj_base_sys_user.NO
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.NAME
     *
     * @return the value of xgj_base_sys_user.NAME
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.NAME
     *
     * @param name the value for xgj_base_sys_user.NAME
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.EMAIL
     *
     * @return the value of xgj_base_sys_user.EMAIL
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.EMAIL
     *
     * @param email the value for xgj_base_sys_user.EMAIL
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.PHONE
     *
     * @return the value of xgj_base_sys_user.PHONE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.PHONE
     *
     * @param phone the value for xgj_base_sys_user.PHONE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.MOBILE
     *
     * @return the value of xgj_base_sys_user.MOBILE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.MOBILE
     *
     * @param mobile the value for xgj_base_sys_user.MOBILE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.USER_TYPE
     *
     * @return the value of xgj_base_sys_user.USER_TYPE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.USER_TYPE
     *
     * @param userType the value for xgj_base_sys_user.USER_TYPE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.PHOTO
     *
     * @return the value of xgj_base_sys_user.PHOTO
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.PHOTO
     *
     * @param photo the value for xgj_base_sys_user.PHOTO
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.LOGIN_IP
     *
     * @return the value of xgj_base_sys_user.LOGIN_IP
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.LOGIN_IP
     *
     * @param loginIp the value for xgj_base_sys_user.LOGIN_IP
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.LOGIN_DATE
     *
     * @return the value of xgj_base_sys_user.LOGIN_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.LOGIN_DATE
     *
     * @param loginDate the value for xgj_base_sys_user.LOGIN_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.LOGIN_FLAG
     *
     * @return the value of xgj_base_sys_user.LOGIN_FLAG
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getLoginFlag() {
        return loginFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.LOGIN_FLAG
     *
     * @param loginFlag the value for xgj_base_sys_user.LOGIN_FLAG
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setLoginFlag(String loginFlag) {
        this.loginFlag = loginFlag == null ? null : loginFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.CREATE_BY
     *
     * @return the value of xgj_base_sys_user.CREATE_BY
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.CREATE_BY
     *
     * @param createBy the value for xgj_base_sys_user.CREATE_BY
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.CREATE_DATE
     *
     * @return the value of xgj_base_sys_user.CREATE_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.CREATE_DATE
     *
     * @param createDate the value for xgj_base_sys_user.CREATE_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.UPDATE_BY
     *
     * @return the value of xgj_base_sys_user.UPDATE_BY
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.UPDATE_BY
     *
     * @param updateBy the value for xgj_base_sys_user.UPDATE_BY
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.UPDATE_DATE
     *
     * @return the value of xgj_base_sys_user.UPDATE_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.UPDATE_DATE
     *
     * @param updateDate the value for xgj_base_sys_user.UPDATE_DATE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.REMARKS
     *
     * @return the value of xgj_base_sys_user.REMARKS
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.REMARKS
     *
     * @param remarks the value for xgj_base_sys_user.REMARKS
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.DEL_FLAG
     *
     * @return the value of xgj_base_sys_user.DEL_FLAG
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.DEL_FLAG
     *
     * @param delFlag the value for xgj_base_sys_user.DEL_FLAG
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.REGISTRATID
     *
     * @return the value of xgj_base_sys_user.REGISTRATID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getRegistratid() {
        return registratid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.REGISTRATID
     *
     * @param registratid the value for xgj_base_sys_user.REGISTRATID
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setRegistratid(String registratid) {
        this.registratid = registratid == null ? null : registratid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.SYSTYPE
     *
     * @return the value of xgj_base_sys_user.SYSTYPE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getSystype() {
        return systype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.SYSTYPE
     *
     * @param systype the value for xgj_base_sys_user.SYSTYPE
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setSystype(String systype) {
        this.systype = systype == null ? null : systype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_user.SYSVERSION
     *
     * @return the value of xgj_base_sys_user.SYSVERSION
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public String getSysversion() {
        return sysversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_user.SYSVERSION
     *
     * @param sysversion the value for xgj_base_sys_user.SYSVERSION
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    public void setSysversion(String sysversion) {
        this.sysversion = sysversion == null ? null : sysversion.trim();
    }
}