package com.xgjgas.gascloud.com.yphx.domain;

import java.io.Serializable;
import java.util.Date;

public class XgjSysRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.OFFICE_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.NAME
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.ENNAME
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String enname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.ROLE_TYPE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.DATA_SCOPE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String dataScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.IS_SYS
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String isSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.USEABLE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String useable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.CREATE_BY
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.CREATE_DATE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.UPDATE_BY
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.UPDATE_DATE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.REMARKS
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xgj_base_sys_role.DEL_FLAG
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xgj_base_sys_role
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.ID
     *
     * @return the value of xgj_base_sys_role.ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.ID
     *
     * @param id the value for xgj_base_sys_role.ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.OFFICE_ID
     *
     * @return the value of xgj_base_sys_role.OFFICE_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getOfficeId() {
        return officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.OFFICE_ID
     *
     * @param officeId the value for xgj_base_sys_role.OFFICE_ID
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setOfficeId(String officeId) {
        this.officeId = officeId == null ? null : officeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.NAME
     *
     * @return the value of xgj_base_sys_role.NAME
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.NAME
     *
     * @param name the value for xgj_base_sys_role.NAME
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.ENNAME
     *
     * @return the value of xgj_base_sys_role.ENNAME
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.ENNAME
     *
     * @param enname the value for xgj_base_sys_role.ENNAME
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setEnname(String enname) {
        this.enname = enname == null ? null : enname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.ROLE_TYPE
     *
     * @return the value of xgj_base_sys_role.ROLE_TYPE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.ROLE_TYPE
     *
     * @param roleType the value for xgj_base_sys_role.ROLE_TYPE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.DATA_SCOPE
     *
     * @return the value of xgj_base_sys_role.DATA_SCOPE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getDataScope() {
        return dataScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.DATA_SCOPE
     *
     * @param dataScope the value for xgj_base_sys_role.DATA_SCOPE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setDataScope(String dataScope) {
        this.dataScope = dataScope == null ? null : dataScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.IS_SYS
     *
     * @return the value of xgj_base_sys_role.IS_SYS
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.IS_SYS
     *
     * @param isSys the value for xgj_base_sys_role.IS_SYS
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys == null ? null : isSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.USEABLE
     *
     * @return the value of xgj_base_sys_role.USEABLE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getUseable() {
        return useable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.USEABLE
     *
     * @param useable the value for xgj_base_sys_role.USEABLE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setUseable(String useable) {
        this.useable = useable == null ? null : useable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.CREATE_BY
     *
     * @return the value of xgj_base_sys_role.CREATE_BY
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.CREATE_BY
     *
     * @param createBy the value for xgj_base_sys_role.CREATE_BY
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.CREATE_DATE
     *
     * @return the value of xgj_base_sys_role.CREATE_DATE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.CREATE_DATE
     *
     * @param createDate the value for xgj_base_sys_role.CREATE_DATE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.UPDATE_BY
     *
     * @return the value of xgj_base_sys_role.UPDATE_BY
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.UPDATE_BY
     *
     * @param updateBy the value for xgj_base_sys_role.UPDATE_BY
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.UPDATE_DATE
     *
     * @return the value of xgj_base_sys_role.UPDATE_DATE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.UPDATE_DATE
     *
     * @param updateDate the value for xgj_base_sys_role.UPDATE_DATE
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.REMARKS
     *
     * @return the value of xgj_base_sys_role.REMARKS
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.REMARKS
     *
     * @param remarks the value for xgj_base_sys_role.REMARKS
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xgj_base_sys_role.DEL_FLAG
     *
     * @return the value of xgj_base_sys_role.DEL_FLAG
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xgj_base_sys_role.DEL_FLAG
     *
     * @param delFlag the value for xgj_base_sys_role.DEL_FLAG
     *
     * @mbg.generated Wed Nov 21 11:24:21 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}