package com.xgjgas.gascloud.com.yphx.dao;

import com.xgjgas.gascloud.com.yphx.domain.XgjMenu;
import com.xgjgas.gascloud.com.yphx.domain.XgjMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XgjMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    long countByExample(XgjMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int deleteByExample(XgjMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int insert(XgjMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int insertSelective(XgjMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    List<XgjMenu> selectByExample(XgjMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    XgjMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") XgjMenu record, @Param("example") XgjMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int updateByExample(@Param("record") XgjMenu record, @Param("example") XgjMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int updateByPrimaryKeySelective(XgjMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_menu
     *
     * @mbg.generated Wed Nov 21 11:30:56 CST 2018
     */
    int updateByPrimaryKey(XgjMenu record);
}