package com.xgjgas.gascloud.com.yphx.dao;

import com.xgjgas.gascloud.com.yphx.domain.XgjSysUser;
import com.xgjgas.gascloud.com.yphx.domain.XgjSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XgjSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    long countByExample(XgjSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int deleteByExample(XgjSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int insert(XgjSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int insertSelective(XgjSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    List<XgjSysUser> selectByExample(XgjSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    XgjSysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") XgjSysUser record, @Param("example") XgjSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int updateByExample(@Param("record") XgjSysUser record, @Param("example") XgjSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int updateByPrimaryKeySelective(XgjSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xgj_base_sys_user
     *
     * @mbg.generated Mon Nov 19 15:54:37 CST 2018
     */
    int updateByPrimaryKey(XgjSysUser record);
}